# Workflow for generating design docs

name: Generate Design Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  srcDocs:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: "20.x"
      - name: JSDoc Action - src
        uses: andstor/jsdoc-action@v1.2.1
        with:
          source_dir: ./src
          recurse: true
          output_dir: ./out/src
      - name: JSDoc Action - utils
        uses: andstor/jsdoc-action@v1.2.1
        with:
          source_dir: ./utils
          recurse: true
          output_dir: ./out/utils
      - name: Push docs to repo
        run: |
          git config --global user.name github-actions[bot]
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ./out
          git commit -a -m "Updating Jsdoc documentation"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
